### ISSUE TITLE
项目目标

### ISSUE THREAD

**Issue by carpediemkc** [carpediemkc/BJX-WMS#1]

**Comment by HeYifan1977** [comment]
1.尝试用迭代的方式进行项目管理。
2.找到合适的合作方。
3.实现仓库标签与金蝶系统数据实时同步。

**Comment by carpediemkc** [comment]
> 1.尝试用迭代的方式进行项目管理。 2.找到合适的合作方。 3.实现仓库标签与金蝶系统数据实时同步。

收到，议题完毕。
